# Copyright 2023 Google. All rights reserved.
#
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

VIVADO_VERSION := 2025.2

BASE_IMAGE := xilinx-vivado-base:$(VIVADO_VERSION)
TOOLS_IMAGE := xilinx-vivado:$(VIVADO_VERSION)

# Host auth token generated by scripts/gen_auth_token.sh; passed to the
# base build as a BuildKit secret (never stored in an image layer).
AUTH_TOKEN_FILE := $(HOME)/.Xilinx/wi_authentication_key

# Slim (web) installer .bin at the repo root; auto-detected, or pass
# INSTALLER=<path> explicitly (must be inside the build context).
INSTALLER ?= $(firstword $(wildcard *.bin))

SHELL := /bin/bash

all:
	@echo "VIVADO_VERSION : $(VIVADO_VERSION)"
	@echo "BASE_IMAGE     : $(BASE_IMAGE)"
	@echo "TOOLS_IMAGE    : $(TOOLS_IMAGE)"
	@echo "AUTH_TOKEN     : $(AUTH_TOKEN_FILE)"
	@echo "INSTALLER      : $(INSTALLER)"
	@echo
	@echo "Targets:"
	@echo "	make auth-token INSTALLER=<slim-installer.bin>  generate auth token"
	@echo "	make build-base                                 build base image (slow, rare)"
	@echo "	make build                                      build tools image (fast)"
	@echo "	make run                                        start Vivado"
.PHONY: all

auth-token:
	./scripts/gen_auth_token.sh $(INSTALLER)
.PHONY: auth-token

build-base: base.stamp
.PHONY: build-base

# Rebuild when the stamp is stale OR the image no longer exists
# (stamps alone lie after `docker rmi`).
base.stamp: docker/base/Dockerfile config/install_config.txt scripts/build.base.sh
	env VIVADO_VERSION=$(VIVADO_VERSION) INSTALLER=$(INSTALLER) \
		AUTH_TOKEN_FILE=$(AUTH_TOKEN_FILE) ./scripts/build.base.sh
	touch $@

build: build.stamp
.PHONY: build

build.stamp: docker/tools/Dockerfile docker/tools/entrypoint.sh \
		docker/udev_stub.c davit/Cargo.toml davit/Cargo.lock \
		$(wildcard davit/src/*.rs) scripts/build.tools.sh base.image.ok
	env VIVADO_VERSION=$(VIVADO_VERSION) ./scripts/build.tools.sh
	touch $@

# Force-refresh base when its image is missing, without rebuilding it
# when only the stamp mtimes changed.
base.image.ok: base.stamp
	@docker image inspect $(BASE_IMAGE) > /dev/null 2>&1 || { \
		echo "Base image $(BASE_IMAGE) missing — rebuilding"; \
		rm -f base.stamp; \
		$(MAKE) base.stamp; \
	}
	@touch $@

xilinx-vivado.$(VIVADO_VERSION).docker.tgz: build.stamp
	docker save $(TOOLS_IMAGE) > $@

save: xilinx-vivado.$(VIVADO_VERSION).docker.tgz
.PHONY: save

clean:
	rm -f *.stamp base.image.ok
.PHONY: clean

run:
	./scripts/run.vivado.sh
.PHONY: run
