# Copyright 2023 Google. All rights reserved.
#
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

VIVADO_VERSION := 2025.2

BASE_IMAGE := xilinx-vivado-base:$(VIVADO_VERSION)
TOOLS_IMAGE := xilinx-vivado:$(VIVADO_VERSION)

# Host auth token generated by scripts/gen_auth_token.sh; passed to the
# base build as a BuildKit secret (never stored in an image layer).
AUTH_TOKEN_FILE := $(HOME)/.Xilinx/wi_authentication_key

# Pre-unpacked slim installer tree, expected at ./Xilinx/$(VIVADO_VERSION)/
INSTALLER_DIR := Xilinx

SHELL := /bin/bash

all:
	@echo "VIVADO_VERSION : $(VIVADO_VERSION)"
	@echo "BASE_IMAGE     : $(BASE_IMAGE)"
	@echo "TOOLS_IMAGE    : $(TOOLS_IMAGE)"
	@echo "AUTH_TOKEN     : $(AUTH_TOKEN_FILE)"
	@echo
	@echo "Targets:"
	@echo "	make auth-token INSTALLER=<slim-installer.bin>  generate auth token"
	@echo "	make build-base                                 build base image (slow, rare)"
	@echo "	make build                                      build tools image (fast)"
	@echo "	make run                                        start Vivado"
.PHONY: all

auth-token:
	./scripts/gen_auth_token.sh $(INSTALLER)
.PHONY: auth-token

build-base: base.stamp
.PHONY: build-base

# Rebuild when the stamp is stale OR the image no longer exists
# (stamps alone lie after `docker rmi`).
base.stamp: docker/base/Dockerfile config/xsetup_config_25.txt
	@if [[ ! -f "$(AUTH_TOKEN_FILE)" ]]; then \
		echo "No auth token at $(AUTH_TOKEN_FILE) — run 'make auth-token INSTALLER=<slim-installer.bin>' first"; \
		exit 1; \
	fi
	@if [[ ! -d "$(INSTALLER_DIR)/$(VIVADO_VERSION)" ]]; then \
		echo "No installer tree at $(INSTALLER_DIR)/$(VIVADO_VERSION)/ — download and unpack the AMD slim installer there"; \
		exit 1; \
	fi
	env DOCKER_BUILDKIT=1 docker build \
		--platform linux/amd64 \
		-t $(BASE_IMAGE) \
		--build-arg VIVADO_VERSION=$(VIVADO_VERSION) \
		--secret id=xilinx_token,src=$(AUTH_TOKEN_FILE) \
		-f docker/base/Dockerfile .
	touch $@

build: build.stamp
.PHONY: build

build.stamp: docker/tools/Dockerfile docker/udev_stub.c base.image.ok
	env DOCKER_BUILDKIT=1 docker build \
		--platform linux/amd64 \
		-t $(TOOLS_IMAGE) \
		--build-arg VIVADO_VERSION=$(VIVADO_VERSION) \
		-f docker/tools/Dockerfile .
	touch $@

# Force-refresh base when its image is missing, without rebuilding it
# when only the stamp mtimes changed.
base.image.ok: base.stamp
	@docker image inspect $(BASE_IMAGE) > /dev/null 2>&1 || { \
		echo "Base image $(BASE_IMAGE) missing — rebuilding"; \
		rm -f base.stamp; \
		$(MAKE) base.stamp; \
	}
	@touch $@

xilinx-vivado.$(VIVADO_VERSION).docker.tgz: build.stamp
	docker save $(TOOLS_IMAGE) > $@

save: xilinx-vivado.$(VIVADO_VERSION).docker.tgz
.PHONY: save

clean:
	rm -f *.stamp base.image.ok
.PHONY: clean

run:
	./scripts/run.vivado.sh
.PHONY: run
